config/routes.rb
TMatthew2::Application.routes.draw do

  namespace :admin do
    resources :employers
    resources :resumes
    resources :projects do
      resources :screenshots
    end
  end

  match 'portfolio' => 'projects#index'
  match 'resume' => 'public#resume', as: 'resume'
  match 'download_resume' => 'public#download_resume', as: 'download_resume'
  match 'about' => 'public#about'
  match 'jwindowcrop' => 'public#jwindowcrop'

  resources :sessions
  match 'login' => 'sessions#new', :as => 'login'
  match 'logout' => 'sessions#destroy', :as => 'logout'

  root to: 'public#index'

end

app/models/employer.rb
class Employer < ActiveRecord::Base
  attr_accessible :position, :title, :published

  # associations
  has_many :projects
  has_many :published_projects, class_name: 'Project', conditions: {published: true}, order: :position
end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :employer_id, :link, :long_description, :position, :poster, :published, :short_description, :title, :permalink, :property_of

  mount_uploader :poster, ProjectPosterUploader

  # associations
  belongs_to :employer
  has_many :screenshots, order: :position
    
end

app/models/resume.rb
class Resume < ActiveRecord::Base
  attr_accessible :file, :height, :page_1_photo, :page_2_photo, :display_photos

  mount_uploader :file, ResumeFileUploader
  mount_uploader :page_1_photo, ResumePagePhotoUploader
  mount_uploader :page_2_photo, ResumePagePhotoUploader

  def self.current
    order('created_at desc').first
  end

end

app/models/screenshot.rb
class Screenshot < ActiveRecord::Base
  attr_accessible :photo, :position, :project_id

  mount_uploader :photo, ScreenshotPhotoUploader

  # associations
  belongs_to :project
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email

  def password=(password_str)
    self.password_salt = BCrypt::Engine.generate_salt
    self.password_digest = BCrypt::Engine.hash_secret(password_str, password_salt)
  end

  def authenticate(password)
    password.present? && password_digest.present? && password_digest == BCrypt::Engine.hash_secret(password, password_salt)
  end

end

app/controllers/admin/employers_controller.rb
class Admin::EmployersController < ApplicationController

  before_filter :login_required

  def index
    @employers = Employer.order(:position)
  end

  def new
    @employer = Employer.new
  end

  def create
    @employer = Employer.new(params[:employer])
    if @employer.save
      redirect_to [:admin, @employer], notice: 'Employer successfully created.'
    else
      render action: 'new'
    end
  end

  def show
    @employer = Employer.find(params[:id])
  end

  def edit
    @employer = Employer.find(params[:id])
  end

  def update
    @employer = Employer.find(params[:id])
    if @employer.update_attributes(params[:employer])
      redirect_to [:admin, @employer], notice: 'Employer successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @employer = Employer.find(params[:id])
    @employer.destroy
    redirect_to admin_employers_path, notice: 'Employer successfully deleted.'
  end

end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < ApplicationController

  before_filter :login_required

  def index
    @projects = Project.order(:employer_id, :position).includes(:employer)
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(params[:project])
    if @project.save
      redirect_to [:admin, @project], notice: 'Project created.'
    else
      render action: 'new'
    end
  end

  def show
    @project = Project.find(params[:id])
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])
    if @project.update_attributes(params[:project])
      redirect_to [:admin, @project], notice: 'Project updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    redirect_to admin_projects_path, notice: 'Project destroyed.'
  end

end

app/controllers/admin/resumes_controller.rb
class Admin::ResumesController < ApplicationController

  before_filter :login_required

  def index
    @resumes = Resume.order('created_at desc')
  end

  def new
    @resume = Resume.new
  end

  def create
    @resume = Resume.new(params[:resume])
    if @resume.save
      redirect_to admin_resumes_path, notice: 'Resume created.'
    else
      render action: 'new'
    end
  end

  def edit
    @resume = Resume.find(params[:id])
  end

  def update
    @resume = Resume.find(params[:id])
    if @resume.update_attributes(params[:resume])
      redirect_to admin_resumes_path, notice: 'Resume updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @resume = Resume.find(params[:id])
    @resume.destroy
    redirect_to admin_resumes_path, notice: 'Resume destroyed.'
  end

end

app/controllers/admin/screenshots_controller.rb
class Admin::ScreenshotsController < ApplicationController

  before_filter :login_required
  before_filter :set_project

  def new
    @screenshot = @project.screenshots.new
  end

  def create
    @screenshot = @project.screenshots.new(params[:screenshot])
    if @screenshot.save
      redirect_to [:admin, @project], notice: 'Screenshot successfully created.'
    else
      render action: 'new'
    end
  end

  def edit
    @screenshot = @project.screenshots.find(params[:id])
  end

  def update
    @screenshot = @project.screenshots.find(params[:id])
    if @screenshot.update_attributes(params[:screenshot])
      redirect_to [:admin, @project], notice: 'Screenshot successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @screenshot = @project.screenshots.find(params[:id])
    @screenshot.destroy
    redirect_to [:admin, @project], notice: 'Screenshot successfully deleted.'
  end

private

  def set_project
    @project = Project.find params[:project_id]
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :current_user

  before_filter :set_default_menu_item

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def login_required
    unless current_user
      session[:redirect_to] = request.fullpath
      flash[:error] = "Login required to see that page."
      redirect_to login_path
    end
  end

  def set_default_menu_item
    @menu_item = ""
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
  	@menu_item = "portfolio"
  	@employers = Employer.where(published: true).order(:position).includes(published_projects: :screenshots)
  end

end

app/controllers/public_controller.rb
class PublicController < ApplicationController

  def index
    @tweets = JSON.parse(`curl "http://api.twitter.com/1/statuses/user_timeline.json?screen_name=tybro0103&count=8"`) rescue []
  end

  def resume
    @menu_item = "resume"
    @resume = Resume.current
  end

  def download_resume
    if @resume = Resume.current
      send_file open(@resume.file.url), type: "application/pdf", filename: 'ResumeTylerBrown.pdf'
    else
      redirect_to resume_path
    end
  end

  def about
    @menu_item = "about"
  end

  def jwindowcrop
    readme_markdown = `curl https://raw.github.com/tybro0103/jWindowCrop/master/README.markdown` rescue ""
    @readme_html = BlueCloth.new(readme_markdown).to_html.html_safe rescue nil
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.where(email: params[:email]).first
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to session[:redirect_to] || root_path
    else
      flash[:error] = "Authentication failed."
      render action: 'new'
    end
  end

  def destroy
    reset_session
    redirect_to root_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/employers/_form.html.erb
<%= form_for [:admin, @employer] do |f| %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :position %>
    <%= f.text_field :position %>
  </div>
  <div class="field">
    <%= f.label :published %>
    <%= f.check_box :published %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
  
<% end %>

app/views/admin/employers/edit.html.erb
<h1>Edit Employer</h1>

<%= render 'form' %>

app/views/admin/employers/index.html.erb
<h1>Employers</h1>

<%= link_to 'New Employer', new_admin_employer_path %>

<table class="admin">
  <tr>
    <th>#</th>
    <th>Title</th>
    <th>Published</th>
    <th></th>
  </tr>
  <% @employers.each do |employer| %> <tr>
    <td><%= employer.position %></td>
    <td><%= employer.title %></td>
    <td><%= employer.published %></td>
    <td>
      <%= link_to 'view', admin_employer_path(employer) %> &bull;
      <%= link_to 'edit', edit_admin_employer_path(employer) %> &bull;
      <%= link_to 'delete', [:admin, employer], method: :delete, confirm: 'Are you sure?' %>
    </td>
  </tr> <% end %>
</table>

app/views/admin/employers/new.html.erb
<h1>New Employer</h1>

<%= render 'form' %>

app/views/admin/employers/show.html.erb
<h1>Employer: <%=@employer.title%></h1>

<%= link_to 'edit', [:edit, :admin, @employer] %>

<div class="attributes">
  <div class="attribute">
    <div class="key">Position</div>
    <div class="value"><%= @employer.position %></div>
  </div>
  <div class="attribute">
    <div class="key">Title</div>
    <div class="value"><%= @employer.title %></div>
  </div>
  <div class="attribute">
    <div class="key">Published</div>
    <div class="value"><%= @employer.published %></div>
  </div>
</div>

app/views/admin/projects/_form.html.erb
<%= form_for [:admin, @project] do |f| %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :employer_id %>
    <%= f.collection_select :employer_id, Employer.all, :id, :title %>
  </div>
  <div class="field">
    <%= f.label :permalink %>
    <%= f.text_field :permalink %>
  </div>
  <div class="field">
    <%= f.label :link %>
    <%= f.text_field :link %>
  </div>
  <div class="field">
    <%= f.label :position %>
    <%= f.text_field :position %>
  </div>
  <div class="field">
    <%= f.label :poster %>
    <%= f.file_field :poster %>
  </div>
  <div class="field">
    <%= f.label :published %>
    <%= f.check_box :published %>
  </div>
  <div class="field">
    <%= f.label :short_description %>
    <%= f.text_area :short_description %>
  </div>
  <div class="field">
    <%= f.label :long_description %>
    <%= f.text_area :long_description %>
  </div>
  <div class="field">
    <%= f.label :property_of %>
    <%= f.text_field :property_of %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/admin/projects/edit.html.erb
<h1>Edit Project</h1>

<%= render 'form' %>

app/views/admin/projects/index.html.erb
<h1>Projects</h1>

<%= link_to 'New Project', new_admin_project_path %>

<table class="admin">
  <tr>
    <th>Employer</th>
    <th>#</th>
    <th>Title</th>
    <th>Published</th>
    <th>Property Of</th>
    <th></th>
  </tr>
  <% @projects.each do |project| %> <tr>
    <td><%= project.employer.try(:title) %></td>
    <td><%= project.position %></td>
    <td><%= project.title %></td>
    <td><%= project.published %></td>
    <td><%= project.property_of %></td>
    <td>
      <%= link_to 'view', admin_project_path(project) %> &bull;
      <%= link_to 'edit', edit_admin_project_path(project) %> &bull;
      <%= link_to 'delete', [:admin, project], method: :delete, confirm: 'Are you sure?' %>
    </td>
  </tr> <% end %>
</table>

app/views/admin/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form' %>

app/views/admin/projects/show.html.erb
<h1>Project: <%=@project.title%></h1>

<%= link_to 'edit', [:edit, :admin, @project] %>

<div class="attributes">
  <div class="attribute">
    <div class="key">Poster</div>
    <div class="value"><%= link_to image_tag(@project.poster.url(:thumb)), @project.poster.url(:framed) %></div>
  </div>
  <div class="attribute">
    <div class="key">Title</div>
    <div class="value"><%=@project.title%></div>
  </div>
  <div class="attribute">
    <div class="key">Employer</div>
    <div class="value"><% if @project.employer %><%= link_to @project.employer.title, [:admin, @project.employer] %><% end %></div>
  </div>
  <div class="attribute">
    <div class="key">Link</div>
    <div class="value"><%=@project.link%></div>
  </div>
  <div class="attribute">
    <div class="key">Position</div>
    <div class="value"><%=@project.position%></div>
  </div>
  <div class="attribute">
    <div class="key">Published</div>
    <div class="value"><%=@project.published%></div>
  </div>
  <div class="attribute">
    <div class="key">Permalink</div>
    <div class="value"><%=@project.permalink%></div>
  </div>
  <div class="attribute">
    <div class="key">Short Description</div>
    <div class="value"><%=@project.short_description%></div>
  </div>
  <div class="attribute">
    <div class="key">Long Description</div>
    <div class="value"><%=@project.long_description%></div>
  </div>
</div>

<br /><br />

<h2>Screenshots</h2>
<%= link_to 'New Screenshot', new_admin_project_screenshot_path(@project) %>
<table class="admin">
  <tr>
    <th>#</th>
    <th>Photo</th>
    <th></th>
  </tr>
  <% @project.screenshots.each do |screenshot| %><tr>
    <td><%= screenshot.position %></td>
    <td><%= link_to image_tag(screenshot.photo.url(:thumb), width: 60), screenshot.photo.url(:large) %></td>
    <td><%= link_to 'edit', edit_admin_project_screenshot_path(@project, screenshot) %></td>
  </tr><% end %>
</table>

<br /><br />

app/views/admin/resumes/_form.html.erb
<%= form_for [:admin, @resume] do |f| %>

  <div class="field">
    <%= f.label :file %>
    <%= f.file_field :file %>
  </div>
  <div class="field">
    <%= f.label :height %>
    <%= f.text_field :height %>
  </div>
  <div class="field">
    <%= f.label :page_1_photo %>
    <%= f.file_field :page_1_photo %>
  </div>
  <div class="field">
    <%= f.label :page_2_photo %>
    <%= f.file_field :page_2_photo %>
  </div>
  <div class="field">
    <%= f.label :display_photos %>
    <%= f.check_box :display_photos %>
  </div>

  <div class="actions">
    <%= f.submit %>
    <% unless @resume.new_record? %>
      <%= link_to 'Delete Resume', [:admin, @resume], method: :delete, confirm: 'Are you sure?' %>
    <% end %>
  </div>

<% end %>

app/views/admin/resumes/edit.html.erb
<h1>Edit Resume</h1>

<%= render 'form' %>

app/views/admin/resumes/index.html.erb
<h1>Resumes</h1>

<%= link_to 'New Resume', new_admin_resume_path %>

<table class="admin">
  <tr>
    <th>Date</th>
    <th>File</th>
    <th>Height</th>
    <th>Display</th>
    <th></th>
  </tr>
  <% @resumes.each do |resume| %><tr>
    <td><%= resume.created_at.strftime('%b %d, %Y') %></td>
    <td><%= link_to resume.file.url, resume.file.url %></td>
    <td><%= resume.height %></td>
    <td><%= resume.display_photos ? 'photos' : 'pdf' %></td>
    <td><%= link_to 'edit', edit_admin_resume_path(resume) %></td>
  </tr> <% end %>
</table>

app/views/admin/resumes/new.html.erb
<h1>New Resume</h1>

<%= render 'form' %>

app/views/admin/screenshots/_form.html.erb
<%= form_for [:admin, @project, @screenshot] do |f| %>

  <div class="field">
    <%= f.label :project_id %>
    <%= f.collection_select :project_id, Project.all, :id, :title %>
  </div>
  <div class="field">
    <%= f.label :photo %>
    <%= f.file_field :photo %>
  </div>
  <div class="field">
    <%= f.label :position %>
    <%= f.text_field :position %>
  </div>

  <div class="actions">
    <%= f.submit %>
    <% unless @screenshot.new_record? %>
      <%= link_to 'Delete Screenshot', [:admin, @project, @screenshot], method: :delete, confirm: 'Are you sure?' %>
    <% end %>
  </div>

<% end %>

app/views/admin/screenshots/edit.html.erb
<h1>Edit Screenshot</h1>

<%= render 'form' %>

app/views/admin/screenshots/new.html.erb
<h1>New Screenshot</h1>

<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TMatthew</title>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,700' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div id="layer_pattern"></div>
  <div id="layer_content">

    <!-- SESSION -->
    <div id="session"><div class="widther">
      <% if current_user %>
        <%= current_user.email %>
        &bull; <%= link_to 'Logout', logout_path %>
      <% else %>
        <%= link_to 'Login', login_path %>
      <% end %>
    </div></div>

    <!-- BANNER -->
    <div id="banner_perspective">
      <div id="banner_bg">
        <div class="widther contain">
          <div id="tag_n_title">
            <a id="title" href="/">TMatthew</a>
            <div id="tag">&gt;&gt; Nerd.find_by_name(&quot;Tyler Brown&quot;).to_web</div>
          </div>
          <div id="main_menu">
            <a href="/portfolio" class="<%=@menu_item=='portfolio' ? 'selected' : ''%>">Portfolio</a>
            <a href="/resume" class="<%=@menu_item=='resume' ? 'selected' : ''%>">Résumé</a>
            <a href="/about" class="<%=@menu_item=='about' ? 'selected' : ''%>">About</a>
          </div>
        </div>
      </div>
    </div>

    <!-- ADMIN MENU -->
    <% if current_user %>
      <div id="admin_menu"><div class="widther">
        <%= link_to 'Employers', admin_employers_path %> &bull;
        <%= link_to 'Projects', admin_projects_path %> &bull;
        <%= link_to 'Resumes', admin_resumes_path %>
      </div></div>
    <% end %>

    <!-- BODY -->
    <div id="body"><div class="widther">
      <%= yield %>
    </div></div>

    <!-- FOOTER -->
    <div id="footer"><div class="widther contain">
      <div id="copyright">Copyright &copy; 2011-<%=Date.today.year%> Tyler Brown</div>
      <div id="blah">TMatthew</div>
    </div></div>    

  </div>

</body>
</html>

app/views/projects/index.html.erb
<% @employers.each do |employer| %> <div class="employer" data-project-count="<%=employer.published_projects.length%>" data-project-index="0">
  <a href="#" class="slider_button" data-direction="prev"></a>
  <a href="#" class="slider_button" data-direction="next"></a>

  <!--projects-->
  <div class="project_window"><div class="projects" style="width:<%=employer.published_projects.length*860%>px;">
    <% employer.published_projects.each do |project| %> <div class="project">
      <!--text column-->
      <div class="text">
        <h3 class="title">
          <%= project.link.present? ? link_to(project.title, project.link, target: '_blank') : project.title %>
        </h3>
        <p class="description"><%=project.long_description%></p>
        <p class="property_of"><%=project.property_of.present? ? "property of #{project.property_of}" : ''%></p>
        <div class="screenshots"><div class="screenshots_scroller" style="width:<%=65*project.screenshots.length.to_i%>px;">
          <% project.screenshots.each do |screenshot| %>
            <%= link_to image_tag(screenshot.photo.url(:thumb)), screenshot.photo.url(:large), rel: "project_#{project.id}" %>
          <% end %>
        </div></div>
      </div>
      <!--poster column-->
      <div class="poster" style="background-image:url(<%=project.poster.url(:framed)%>);"></div>
    </div> <% end %>
  </div></div>

  <!--pages-->
  <div class="pages"><div class="pages_con">
    <% employer.published_projects.each_with_index do |project, index| %>
      <div class="page" data-selected="<%=index==0%>" data-page="<%=index%>"></div>
    <% end %>
  </div></div>

  <h2 class="employer_title"><%=employer.title%> Projects</h2>

</div> <% end %>